services:
  - type: web
    name: tele-medicine
    env: docker             # Render builds using your Dockerfile
    dockerfilePath: Dockerfile
    plan: free
    branch: main
    envVars:
      - key: PORT
        value: 10000
      
